-- Migration generated by dbdev add at: 2026-07-06 08:09:08
-- Extension: pgho_payments
-- Default version: 0.0.1
-- Comment: Ledger-first payments: double-entry ledger, wallets, catalog, orders, subscriptions
------------------------------------
-- Delete existing extension if installed
drop extension if exists "pgho_payments";
-- Create the extension
create extension "pgho_payments" schema "pgho_payments" version '0.0.1';
-- Setting default version to:0.0.1
select pgtle.set_default_version('pgho_payments', '0.0.1');
